### ISSUE TITLE
Google Drive account permissions

### ISSUE THREAD

**Issue by ednerd** [contentsync/SketchContentSync.sketchplugin#25]
The company I work for has a corporate Google Drive account and I'm wondering what kind of additional permissions need to be set in order to use sheets on there?

**Comment by dbrody** [comment]
@ednerd It should be the same for a corporate Google Drive account. You would auth the same way with your company google account and create projects the same. The platform may ask you for additional permissions if you have not yet authorized it. Also, in order to see previous documents, you will want to click the blue alert message under the Spreadsheet Dropdown seen here:

![screen shot 2017-01-19 at 6 32 09 pm](https://cloud.githubusercontent.com/assets/210322/22133549/b8431954-de75-11e6-992e-05fb8866fc01.png)

In terms of organizations as a whole. Stay tuned, there is a pretty large update coming that will support creating organizations to share projects, have common billing, and more.

**Comment by ednerd** [comment]
@dbrody I must have set up the account incorrectly. I don't see the blue alert message under the dropdown.
![screen shot 2017-01-20 at 8 41 28 am](https://cloud.githubusercontent.com/assets/1708548/22157433/93d53a44-deec-11e6-99a0-09ba938d6914.png)

**Comment by ednerd** [comment]
Both my personal gmail address and my "work" address have that **_Requires Plus Plans_** badge instead of **_Requires Spreadsheet Access_**. So, I tried with a new gmail address and that worked fine. I'm wondering if my earlier accounts were limited somehow when created?

**Comment by dbrody** [comment]
@ednerd We just launched a major update to flip everybody to have the ability to create organizations and share projects. Part of that update fixes many of the plan issues you were seeing since Plans are no longer relevant as we are firm believers in letting people use this as much as they'd like without extra cost each time. Hopefully this helps. Let me know if you continue to encounter this issue as I'll be happy to dive in deeper and help you solve any remaining problems.

**Comment by ednerd** [comment]
@dbrody Looks great! I was able to delete projects! Unfortunately, I am still unable to get the perms right on my other contractor account. I get this error even after allowing additional permissions to manage Drive and access spreadsheets. I appreciate you looking into this.
![screen shot 2017-01-24 at 4 56 48 pm](https://cloud.githubusercontent.com/assets/1708548/22273630/9baa6bfa-e256-11e6-8e40-58a34207e291.png)

**Comment by dbrody** [comment]
@ednerd Hm, sorry for the inconvenience.

Can you follow up with us at support@contentsync.io additional help? I'd like to dive in to your case but don't want to share any of your personal information on this forum.

Thanks,
David

**Comment by ednerd** [comment]
Yes. Thank you.
